# Generated by Django 5.1.4 on 2026-07-18 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_must_change_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='admin_takeover_pending',
            field=models.BooleanField(default=False),
        ),
    ]
