# Generated by Django 5.1.4 on 2026-07-04 12:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('children', '0007_child_status_archived_to_inactive'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyFormTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_type', models.CharField(choices=[('consent', 'Consent Form'), ('clinical_interview', 'Clinical Interview Form'), ('problem_checklist', 'Problem Checklist'), ('self_report_gov', 'Self-Report (Government Form)')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('fields', models.JSONField(blank=True, default=list)),
                ('version', models.PositiveIntegerField(default=1)),
                ('attestation', models.BooleanField(default=False, help_text='This form is agency-authored or an official government form, not a published assessment instrument.')),
                ('attested_at', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tbl_agency_form_template',
                'ordering': ['form_type', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ClinicalInterviewRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.JSONField(blank=True, default=dict)),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_interviews', to='children.child')),
                ('interviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interviews_conducted', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interview_records', to='clinical.agencyformtemplate')),
            ],
            options={
                'db_table': 'tbl_clinical_interview_record',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ConsentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signer_name', models.CharField(blank=True, max_length=150)),
                ('signer_relationship', models.CharField(blank=True, max_length=100)),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('scan', models.FileField(blank=True, null=True, upload_to='consents/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('signed', 'Signed'), ('declined', 'Declined')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to='children.child')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consents_recorded', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consent_records', to='clinical.agencyformtemplate')),
            ],
            options={
                'db_table': 'tbl_consent_record',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='InstrumentCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('publisher', models.CharField(blank=True, max_length=200)),
                ('category', models.CharField(choices=[('cognitive', 'Cognitive'), ('behavioral', 'Behavioral'), ('projective', 'Projective'), ('personality', 'Personality'), ('developmental', 'Developmental'), ('achievement', 'Achievement'), ('other', 'Other')], default='other', max_length=30)),
                ('age_range', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalog_instruments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tbl_instrument_catalog',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='ProblemEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('category', models.CharField(blank=True, max_length=100)),
                ('identified_on', models.DateField(default=django.utils.timezone.localdate)),
                ('resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='children.child')),
                ('logged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='problems_logged', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tbl_problem_entry',
                'ordering': ['resolved', '-identified_on', '-id'],
            },
        ),
    ]
