# Generated by Django 5.1.4 on 2026-07-04 12:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0007_child_status_archived_to_inactive'),
        ('clinical', '0002_seed_catalog_from_questionnaires'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PreAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In progress'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pre_assessments', to='children.child')),
                ('consent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pre_assessments', to='clinical.consentrecord')),
                ('instruments', models.ManyToManyField(blank=True, related_name='pre_assessments', to='clinical.instrumentcatalog')),
                ('interview', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pre_assessments', to='clinical.clinicalinterviewrecord')),
                ('psychologist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pre_assessments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tbl_pre_assessment',
                'ordering': ['-date', '-id'],
            },
        ),
    ]
