# Generated by Django 5.1.4 on 2026-07-04 13:18

import clinical.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0008_remove_progressnote_author_remove_progressnote_child_and_more'),
        ('clinical', '0003_preassessment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PsychologicalReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=clinical.models.report_upload_path)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('report_type', models.CharField(choices=[('initial', 'Initial Evaluation'), ('progress', 'Progress Report'), ('final', 'Final Report'), ('other', 'Other')], default='other', max_length=20)),
                ('coverage', models.CharField(blank=True, help_text="Session/date coverage, e.g. 'Sessions 1-3, Jan-Mar 2026'", max_length=150)),
                ('extracted_text', models.TextField(blank=True)),
                ('ai_summary', models.TextField(blank=True, null=True)),
                ('ai_summary_confirmed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='psych_reports', to=settings.AUTH_USER_MODEL)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='psych_reports', to='children.child')),
            ],
            options={
                'db_table': 'tbl_psychological_report',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RemarkNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remarks_written', to=settings.AUTH_USER_MODEL)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remarks', to='children.child')),
            ],
            options={
                'db_table': 'tbl_remark_note',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ResultEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(help_text="Findings in the psychologist's own words")),
                ('classification', models.CharField(blank=True, help_text="Free-text classification, the psychologist's own words", max_length=150)),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_entries', to='children.child')),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='result_entries', to=settings.AUTH_USER_MODEL)),
                ('instrument', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='result_entries', to='clinical.instrumentcatalog')),
                ('pre_assessment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='result_entries', to='clinical.preassessment')),
            ],
            options={
                'db_table': 'tbl_result_entry',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TreatmentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectives', models.TextField()),
                ('interventions', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('revised', 'Revised')], default='active', max_length=20)),
                ('review_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treatment_plans', to=settings.AUTH_USER_MODEL)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatment_plans', to='children.child')),
            ],
            options={
                'db_table': 'tbl_treatment_plan',
                'ordering': ['-created_at'],
            },
        ),
    ]
