# Generated by Django 5.1.4 on 2026-07-05 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0004_psychologicalreport_remarknote_resultentry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultentry',
            name='baseline_category',
            field=models.CharField(blank=True, choices=[('Needs Counseling', 'Needs Counseling'), ('Good Assessment', 'Good Assessment')], max_length=30),
        ),
    ]
