# Generated by Django 5.1.4 on 2026-07-05 01:28

import clinical.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0010_backfill_case_status'),
        ('clinical', '0005_resultentry_baseline_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=clinical.models.case_referral_upload_path)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('extracted_text', models.TextField(blank=True)),
                ('ai_summary', models.TextField(blank=True, null=True)),
                ('ai_summary_confirmed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_studies', to='children.child')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_studies_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tbl_case_study',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OpinionnaireInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=clinical.models._invite_token, editable=False, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('answers', models.JSONField(blank=True, default=dict)),
                ('expires_at', models.DateTimeField()),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opinionnaire_invites', to='children.child')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opinionnaire_invites_created', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opinionnaire_invites', to='clinical.agencyformtemplate')),
            ],
            options={
                'db_table': 'tbl_opinionnaire_invite',
                'ordering': ['-created_at'],
            },
        ),
    ]
