# Generated by Django 5.1.4 on 2026-07-14 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0006_casestudy_opinionnaireinvite'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencyformtemplate',
            name='body',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='clinicalinterviewrecord',
            name='respondent',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
