# Generated by Django 5.1.4 on 2026-07-15 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0007_agencyformtemplate_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrumentcatalog',
            name='audience',
            field=models.CharField(choices=[('child', 'For children'), ('adoptive_parent', 'For prospective adoptive parents'), ('both', 'Both')], default='child', max_length=20),
        ),
    ]
