# Generated by Django 5.1.4 on 2026-08-26 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0017_child_psgc_barangay_child_psgc_municipality_and_more'),
        ('clinical', '0009_rename_casestudy_casereferral'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SelfReportFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('source', models.CharField(choices=[('lexicon', 'Phrase list'), ('model', 'Local model')], max_length=20)),
                ('matched', models.CharField(blank=True, help_text="The phrase that fired, or the model's one-line reason", max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='self_report_flags', to='children.child')),
                ('invite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='clinical.opinionnaireinvite')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='self_report_flags_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tbl_self_report_flag',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['child', 'reviewed_at'], name='tbl_self_re_child_i_671e81_idx')],
                'constraints': [models.UniqueConstraint(fields=('invite', 'question', 'source'), name='uniq_self_report_flag_per_question_source')],
            },
        ),
    ]
