# Generated by Django 5.1.4 on 2026-08-18 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Municipality",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "psgc_code",
                    models.CharField(db_index=True, max_length=12, unique=True),
                ),
                ("name", models.CharField(db_index=True, max_length=120)),
            ],
            options={
                "db_table": "tbl_municipality",
                "ordering": ["name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Province",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "psgc_code",
                    models.CharField(db_index=True, max_length=12, unique=True),
                ),
                ("name", models.CharField(db_index=True, max_length=120)),
            ],
            options={
                "db_table": "tbl_province",
                "ordering": ["name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Barangay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "psgc_code",
                    models.CharField(db_index=True, max_length=12, unique=True),
                ),
                ("name", models.CharField(db_index=True, max_length=120)),
                (
                    "municipality",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="barangays",
                        to="locations.municipality",
                    ),
                ),
            ],
            options={
                "db_table": "tbl_barangay",
                "ordering": ["name"],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="municipality",
            name="province",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="municipalities",
                to="locations.province",
            ),
        ),
    ]
