# Generated by Django 5.1.4 on 2026-07-04 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AISetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('feature_brief', models.BooleanField(default=True)),
                ('feature_doc_intelligence', models.BooleanField(default=True)),
                ('feature_remark_polish', models.BooleanField(default=True)),
                ('feature_census_narrative', models.BooleanField(default=True)),
                ('ollama_url', models.URLField(default='http://localhost:11434')),
                ('model_name', models.CharField(default='qwen2.5:7b-instruct', max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tbl_ai_setting',
            },
        ),
        migrations.CreateModel(
            name='AIJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(choices=[('brief', 'Pre-Session Brief'), ('doc_intelligence', 'Report Document Intelligence'), ('remark_polish', 'Remark Polishing'), ('census_narrative', 'Census Narrative')], max_length=30)),
                ('input_ref', models.CharField(blank=True, max_length=150)),
                ('output_text', models.TextField(blank=True)),
                ('model_used', models.CharField(blank=True, max_length=100)),
                ('latency_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('ok', models.BooleanField(default=True)),
                ('error', models.CharField(blank=True, max_length=255)),
                ('accepted', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tbl_ai_job',
                'ordering': ['-created_at'],
            },
        ),
    ]
