# Generated by Django 5.1.4 on 2026-07-09 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aijob',
            name='job_type',
            field=models.CharField(choices=[('brief', 'Pre-Session Brief'), ('doc_intelligence', 'Report Document Intelligence'), ('remark_polish', 'Remark Polishing'), ('census_narrative', 'Census Narrative'), ('case_study', 'Case Study Summary')], max_length=30),
        ),
    ]
