# Generated by Django 5.1.4 on 2026-07-09 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_alter_aijob_job_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='aijob',
            name='outcome',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted as-is'), ('edited', 'Edited then used'), ('discarded', 'Discarded')], default='pending', max_length=10),
        ),
    ]
