# Generated by Django 5.1.4 on 2026-07-04 09:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0005_goal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='current_placement',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='child',
            name='education_level',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='child',
            name='medical_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='child',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='children/photos/'),
        ),
        migrations.AddField(
            model_name='child',
            name='referral_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='child',
            name='referral_source',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='child',
            name='case_type',
            field=models.CharField(blank=True, choices=[('Adoption', 'Adoption'), ('Foster Care', 'Foster Care'), ('Kinship Care', 'Kinship Care'), ('Residential Care', 'Residential Care'), ('Family Tracing & Reunification', 'Family Tracing & Reunification'), ('Independent Living', 'Independent Living')], max_length=150),
        ),
        migrations.AlterField(
            model_name='child',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20),
        ),
        migrations.CreateModel(
            name='TerminationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('reason_category', models.CharField(choices=[('Reunified with family', 'Reunified with family'), ('Adoption finalized', 'Adoption finalized'), ('Transferred to another agency', 'Transferred to another agency'), ('Aged out of program', 'Aged out of program'), ('Services completed', 'Services completed'), ('Other', 'Other')], max_length=50)),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terminations', to='children.child')),
                ('terminated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='terminations_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tbl_termination_record',
                'ordering': ['-created_at'],
            },
        ),
    ]
