# Generated by Django 5.1.4 on 2026-07-04 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0007_child_status_archived_to_inactive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progressnote',
            name='author',
        ),
        migrations.RemoveField(
            model_name='progressnote',
            name='child',
        ),
        migrations.DeleteModel(
            name='Goal',
        ),
        migrations.DeleteModel(
            name='ProgressNote',
        ),
    ]
