# Generated by Django 5.1.4 on 2026-07-05 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0008_remove_progressnote_author_remove_progressnote_child_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='case_status',
            field=models.CharField(choices=[('pre_assessment', 'Pre-Assessment'), ('counseling', 'Counseling'), ('terminated', 'Terminated')], default='pre_assessment', max_length=20),
        ),
    ]
