# Generated by Django 5.1.4 on 2026-07-08 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0010_backfill_case_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='case_category',
            field=models.CharField(blank=True, choices=[('Abandoned', 'Abandoned'), ('Foundling', 'Foundling'), ('Surrendered', 'Surrendered'), ('Neglected', 'Neglected'), ('Dependent', 'Dependent'), ('Orphaned', 'Orphaned'), ('Victim of Physical Abuse', 'Victim of Physical Abuse'), ('Victim of Sexual Abuse', 'Victim of Sexual Abuse'), ('Victim of OSAEC/CSAEM', 'Victim of OSAEC/CSAEM'), ('Trafficked', 'Trafficked'), ('CICL', 'CICL'), ('Children at Risk (CAR)', 'Children at Risk (CAR)'), ('Children in Street Situation', 'Children in Street Situation'), ('Victim of Child Labor', 'Victim of Child Labor'), ('Child With Disability', 'Child With Disability'), ('Child Living with HIV', 'Child Living with HIV'), ('Indigenous Peoples', 'Indigenous Peoples'), ('Others', 'Others')], max_length=50),
        ),
    ]
