# Generated by Django 5.1.4 on 2026-07-15 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0011_child_case_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='recommendation',
            field=models.TextField(blank=True),
        ),
    ]
