# Generated by Django 5.1.4 on 2026-07-15 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0012_child_recommendation'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='child',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='child',
            name='middle_initial',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
