# Generated by Django 5.1.4 on 2026-07-15 15:14

from django.db import migrations


def split_names(apps, schema_editor):
    Child = apps.get_model("children", "Child")
    for c in Child.objects.all():
        parts = (c.fullname or "").split()
        if not parts:
            continue
        c.last_name = parts[-1] if len(parts) > 1 else ""
        c.first_name = " ".join(parts[:-1]) if len(parts) > 1 else parts[0]
        c.save(update_fields=["first_name", "last_name"])


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0013_child_first_name_child_last_name_and_more'),
    ]

    operations = [
        migrations.RunPython(split_names, migrations.RunPython.noop),
    ]
