# Generated by Django 5.1.4 on 2026-07-17 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0014_split_existing_fullnames'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='birth_status',
            field=models.CharField(blank=True, choices=[('Marital', 'Marital'), ('Non-Marital', 'Non-Marital'), ('Child', 'Child')], max_length=20),
        ),
        migrations.AddField(
            model_name='child',
            name='date_of_admission',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='child',
            name='date_of_placement_to_custodian',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='child',
            name='legal_status',
            field=models.CharField(blank=True, choices=[('With Issued CDCLAA', 'With Issued CDCLAA'), ('With IVC', 'With IVC'), ('Judicially Declared Abandoned', 'Judicially Declared Abandoned')], max_length=50),
        ),
        migrations.AddField(
            model_name='child',
            name='place_of_birth_or_found',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='child',
            name='type_of_adoption',
            field=models.CharField(blank=True, choices=[('Regular', 'Regular'), ('Domestic Relative', 'Domestic Relative'), ('Step-parent', 'Step-parent'), ('Adult', 'Adult'), ('SIBRA', 'SIBRA'), ('ICA Relative', 'ICA Relative'), ('IP', 'IP'), ('Foster-Adopt', 'Foster-Adopt')], max_length=50),
        ),
        migrations.AlterField(
            model_name='child',
            name='case_category',
            field=models.CharField(blank=True, choices=[('Surrendered', 'Surrendered'), ('Abandoned', 'Abandoned'), ('Dependent', 'Dependent'), ('Neglected', 'Neglected'), ('Without Known Parents', 'Without Known Parents'), ('Orphan', 'Orphan')], max_length=50),
        ),
    ]
