# Generated by Django 5.1.4 on 2026-08-18 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("children", "0015_child_birth_status_child_date_of_admission_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="child",
            name="birth_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Marital", "Marital"),
                    ("Non-Marital", "Non-Marital"),
                    ("Child", "Child"),
                    ("N/A", "N/A"),
                ],
                max_length=20,
            ),
        ),
    ]
