# Generated by Django 5.1.4 on 2026-08-18 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("children", "0016_birth_status_na"),
    ]

    operations = [
        migrations.AddField(
            model_name="child",
            name="psgc_barangay",
            field=models.CharField(blank=True, db_index=True, max_length=12),
        ),
        migrations.AddField(
            model_name="child",
            name="psgc_municipality",
            field=models.CharField(blank=True, db_index=True, max_length=12),
        ),
        migrations.AddField(
            model_name="child",
            name="psgc_province",
            field=models.CharField(blank=True, db_index=True, max_length=12),
        ),
    ]
