# Generated by Django 5.1.4 on 2026-08-26 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assistantsetting',
            name='feature_brief',
        ),
        migrations.RemoveField(
            model_name='assistantsetting',
            name='feature_census_narrative',
        ),
        migrations.RemoveField(
            model_name='assistantsetting',
            name='feature_doc_intelligence',
        ),
        migrations.RemoveField(
            model_name='assistantsetting',
            name='feature_remark_polish',
        ),
        migrations.AlterField(
            model_name='assistantsetting',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
