# Generated by Django 5.1.4 on 2026-08-26 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0002_remove_assistantsetting_feature_brief_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistantjob',
            name='job_type',
            field=models.CharField(choices=[('brief', 'Pre-Session Brief'), ('doc_intelligence', 'Document Summary'), ('remark_polish', 'Remark Polishing'), ('census_narrative', 'Census Narrative'), ('chat', 'Chatbot Question')], max_length=30),
        ),
    ]
