# Generated by Django 5.1.4 on 2026-08-26 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0003_alter_assistantjob_job_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistantjob',
            name='job_type',
            field=models.CharField(choices=[('brief', 'Pre-Session Brief'), ('doc_intelligence', 'Document Summary'), ('remark_polish', 'Remark Polishing'), ('census_narrative', 'Census Narrative'), ('chat', 'Chatbot Question'), ('self_report', 'Self-Report Check')], max_length=30),
        ),
    ]
