# Generated by Django 5.1.4 on 2026-07-08 14:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SamdAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('in_progress', 'In progress'), ('completed', 'Completed')], default='in_progress', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='samd_assessments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tbl_samd_assessment',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SamdResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_key', models.CharField(max_length=10)),
                ('compliance', models.CharField(blank=True, choices=[('yes', 'Yes'), ('not', 'Not'), ('na', 'N/A')], max_length=10)),
                ('remarks', models.TextField(blank=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='samd.samdassessment')),
            ],
            options={
                'db_table': 'tbl_samd_response',
                'constraints': [models.UniqueConstraint(fields=('assessment', 'item_key'), name='unique_samd_response_per_item')],
            },
        ),
    ]
